name: collection
version: 1.18.0
description: Collections and utilities functions and classes related to collections.
repository: https://github.com/dart-lang/collection

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
